apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yyquupv87-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yyquupv87-python 
  name: yyquupv87-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yyquupv87-python 
